### ISSUE TITLE
what FtoV means?

### ISSUE THREAD

**Issue by JIMXGtamods** [maybegreat48/GTA-V-Script-Decompiler#16]
I want know what is FtoV?
Example: FtoV(SYSTEM::VMAG(Var4))

**Comment by Lucas7yoshi** [comment]
Float to vector
which I think means it makes a vector from a float with XYZ = to the float

**Comment by JIMXGtamods** [comment]
how we do this? c++ or c#?

**Comment by JIMXGtamods** [comment]
> Float to vector which I think means it makes a vector from a float with XYZ = to the float

Thank you!
