### ISSUE TITLE
Crashing at .ysc for GTAV

### ISSUE THREAD

**Issue by 0xEmiil** [maybegreat48/GTA-V-Script-Decompiler#22]
Im not a .net dev so i really dont know why its happening
Every time i want to open a .ysc for example freemode.ysc it crashes with this error

![image](https://github.com/user-attachments/assets/b46d274d-8b24-4262-b648-7958250c955c)

**Comment by maybegreat48** [comment]
Are you building the latest release from source? And have you unchecked RDR2 mode?

**Comment by 0xEmiil** [comment]
> Are you building the latest release from source? And have you unchecked RDR2 mode?

Yep, this is my options
![image](https://github.com/user-attachments/assets/6917a3f4-4d34-4c64-9a83-bb262f5c037f)

and i just build the lastest code or at least the one in f4139cce116b1b74133599c10973197a089f9647

**Comment by maybegreat48** [comment]
>  Every time i want to open a .ysc for example freemode.ysc it crashes with this error

You're supposed to extract ("decompress") the YSC using codewalker. OpenIV doesn't work anymore

**Comment by 0xEmiil** [comment]
> > Every time i want to open a .ysc for example freemode.ysc it crashes with this error
> 
> You're supposed to extract ("decompress") the YSC using codewalker. OpenIV doesn't work anymore

Ohhh, ill tryy Thanks for the Replyy !
