### ISSUE TITLE
Problem when decompiling Freemode and Other Scripts

### ISSUE THREAD

**Issue by YimMenuTheBest** [maybegreat48/GTA-V-Script-Decompiler#25]
In update 1.70, for some reason I am not managing to decompile 3 ysc files out of the 1100 that are currently there, the error I get is the following:
![image](https://github.com/user-attachments/assets/42f4996c-115c-460a-84b0-b411c26784cc)

this only happens with these 3 scripts:

```
freemode.ysc
fm_content_bussines_battles.ysc
fm_content_sightseeing.ysc
```

**Comment by maybegreat48** [comment]
This should be fixed now
