### ISSUE TITLE
Feature Request: option to put enums as comments instead of replacing the value 

### ISSUE THREAD

**Issue by Lucas7yoshi** [maybegreat48/GTA-V-Script-Decompiler#5]
or vice versa really, would be a nice to have for the sake of "preserving the code functionally". 

example:

PED::SET_PED_COMBAT_ATTRIBUTES(uLocal_3050[13], BF_Aggressive, true);

to

PED::SET_PED_COMBAT_ATTRIBUTES(uLocal_3050[13], 13 /*BF_Aggressive*/, true);

or

PED::SET_PED_COMBAT_ATTRIBUTES(uLocal_3050[13], BF_Aggressive /*13*/, true);

this would save having to dig around the source enums or docs to replicate something accurately while still allowing for at-a-glance information

**Comment by maybegreat48** [comment]
Note that substitution is still the default behavior
