### ISSUE TITLE
Some conditions seems wrongly decompiled

### ISSUE THREAD

**Issue by Apokalypt** [maybegreat48/GTA-V-Script-Decompiler#9]
I may be wrong, but in many cases I find a comparison that seems illogical, especially when compared with the behavior of the game...

We can see in several files, conditions with this format : ``\(![\w\d]* == [-2-9][\d]*\)`` ( e.g. ``(!iParam0 == 3)`` )
But if we try to understand the code, we can easily understand that the condition cannot be evaluated to "true":
- !0 = 1
- !n = 0 ( with n != 0 )

I'm pretty sure that instead of being ``(!iParam0 == 3)`` it should be ``(!(iParam0 == 3))`` OR ``(iParam0 != 3)``... Do you know if it's normal and I'm missing something or is it really a decompilation error ?

N.B. : You can see these kind of conditions in several files like "michael3.c" ( example : line 106597 ``!iParam8 == -1``), "base_carmod.c", "wizard_arcade.c", ...

Decompiler version : the last one (built with your last modifications)
Decompiler options : Default

**Comment by maybegreat48** [comment]
By the way, are you from the GTA glitching scene?

**Comment by Apokalypt** [comment]
Yes, I was very active some time ago. 
Now I'm working a little bit more in the shadow since I'm trying to make tools for glitchers but it takes time...

Why do you ask? Do you need information about something?

**Comment by maybegreat48** [comment]
I think I've found a workaround for SP2MP, but I don't have a non-jailbroken PS4 anymore to test stuff
You can contact me on Matrix: @qwlfjdekngh:matrix.org
